# Generated by Django 5.2.4 on 2025-07-13 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='tickets_available',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('VIP', 'VIP'), ('BALCONY', 'Balcony'), ('STANDART', 'Standart')], max_length=10)),
                ('is_sold', models.BooleanField(default=False)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('bought_at', models.DateTimeField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.show')),
            ],
        ),
    ]
