# Generated by Django 5.2.4 on 2025-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_galleryimage_sliderimage_remove_ticket_is_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='place',
            field=models.CharField(default='Divadlo Kámen', max_length=100),
        ),
    ]
