# Generated by Django 5.2.4 on 2025-10-05 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_show_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bought_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
