# Generated by Django 5.2.4 on 2025-10-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ticket_bought_at_ticket_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buyer_email',
            field=models.EmailField(blank=True, default='unknown@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buyer_name',
            field=models.CharField(default='Ivan', max_length=100),
        ),
    ]
